### ISSUE TITLE
Update the product schema and add review schema 

### ISSUE THREAD

**Issue by Noureldin2303** [makhalifa/Makask_Backend#1]
productSchema(
    {
        _id: { type: String, required: true, unique: true },
        sellerid: { type: Types.ObjectId, required: true, ref: 'sellers' },
        title: { type: String, required: true },
        category: { type: String, required: true },
        sub_category: { type: String, required: true },
        price: { type: Number, required: true },
        description: { type: String },
        stock: {
            available: { type: Number },
            available_colors: { type: Array },
            available_sizes: { type: Array },
        },
        ratings: {
            type: mongoose.Mixed,
            // Each star level is represented in the ratings object
            1: Number, //  the weight of that star level
            2: Number,
            3: Number,
            4: Number,
            5: Number,
            default: { 1: 1, 2: 1, 3: 1, 4: 1, 5: 1 }
        },
        brand: { type: String },
        reviews: { type: Array<Types.ObjectId>, ref: 'reviews' },

        images: { type: Array<String> },
        prova_images: { type: Array },

        created_at: { type: Date, default: Date.now },
    },
    { versionKey: false })

     
    reviewSchema(
        {
            _id: { type: String, required: true, unique: true },
            customerid: { type: Types.ObjectId, required: true, ref: 'customers' },
            name: { type: String, "required": true },
            photo: { type: String, "required": true },
            rating: { type: Number },
            description: { type: String },
            created_at: { type: Date, default: Date.now },
        }
    )

**Comment by makhalifa** [comment]
Can't copy and paste ⚠
**explosion** will happen in the code 🤕🌋

Make your issue clear and write the line which need update 🙂

@Noureldin2303

**Comment by AbdelrahmanEmbaby** [comment]
productSchema(
{
    _id: { type: String, required: true, unique: true },
    sellerid: { type: Types.ObjectId, required: true, ref: 'sellers' },
    title: { type: String, required: true },
    category: { type: String, required: true },
    sub_category: { type: String, required: true },
    description: { type: String },
    stock: { type: Array<Types.ObjectId>, ref: 'stock' },
    reviews: { type: Array<Types.ObjectId>, ref: 'reviews' },
    created_at: { type: Date, default: Date.now },
},
{ versionKey: false })

stockschema(
    {
        color: { type: String, required: true },
        sizes: { type: Array<Types.ObjectId>, ref: 'size' },
        image: { type: Array, required: true },
        prova_image: { type: String, required: true },
        price: priceschema,
    }
)

sizeschema(
    {
        size: { type: String, required: true },
        stock: { type: Number, required: true }
    }
)

priceschema(
    {
        price: { type: Number, required: true },
        discount: { type: Number, required: true, min:0, max:100 },
        default: {discount: 0}
    }
)

reviewSchema(
    {
        _id: { type: String, required: true, unique: true },
        customerid: { type: Types.ObjectId, required: true, ref: 'customers' },
        rating: { type: Number, min:1, max:5 },
        description: { type: String },
        created_at: { type: Date, default: Date.now },
    }
)

trendycolors: ["","","","","",""]

samples = [
    {
        _id: "63f8dc106b10e4ae3d6b353f",
        sellerid: "62d8dc106b22e4ae35lb353f",
        title: "Recycled Granite Pizza",
        category: "shirt",
        sub_category: "t-shirt",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type",
        stock: [
            {
                color: "red",
                sizes: [
                    {
                        size: "XL",
                        stock: 1200
                    },
                    {
                        size: "S",
                        stock: 200
                    },
                ],
                image: [
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
                ],
                prova_image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                price: {
                    price: 700,
                    discount: 20,
                },
            },
            {
                color: "green",
                sizes: [
                    {
                        size: "3XL",
                        stock: 1800
                    },
                    {
                        size: "M",
                        stock: 500
                    },
                ],
                image: [
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
                ],
                prova_image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                price: {
                    price: 600,
                    discount: 20,
                },
            },
        ],
        reviews: [
            {
                _id: "63f4g6106b12zxae3d11b512",
                customerid: "6d13g61061m9z23e3dbvb512",
                rating: 4,
                description: "Lorem Ipsum is simply dummy text of the printing and typesetting",
            },
            {
                _id: "63n4g6106b1cczx1e1vd1zb512",
                customerid: "6d1316106179z20e3dbvf512",
                rating: 3,
                description: "Lorem Ipsum is simply dummy text of the printing and typesetting",
            },
        ],
    },
    {
        _id: "63f8dc106b10e4ae3d6b353g",
        sellerid: "62d8dc106b22e4ae35lb353g",
        title: "Recycled Granite Pizza",
        category: "shirt",
        sub_category: "t-shirt",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type",
        stock: [
            {
                color: "blue",
                sizes: [
                    {
                        size: "5XL",
                        stock: 100
                    },
                    {
                        size: "XS",
                        stock: 2080
                    },
                ],
                image: [
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
                ],
                prova_image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                price: {
                    price: 200,
                    discount: 10,
                },
            },
            {
                color: "orange",
                sizes: [
                    {
                        size: "3XL",
                        stock: 1800
                    },
                    {
                        size: "M",
                        stock: 500
                    },
                ],
                image: [
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                    "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
                ],
                prova_image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
                price: {
                    price: 150,
                    discount: 8,
                },
            },
        ],
        reviews: [
            {
                _id: "63f4g6106b12zxae3d11b525",
                customerid: "6d13g61061m9z23e3dbvb537",
                rating: 5,
                description: "Lorem Ipsum is simply dummy text of the printing and typesetting",
            },
            {
                _id: "63n4g6106b1cczx1e1vd1xcf12",
                customerid: "6d1316106179z20e3dbm1t52",
                rating: 5,
                description: "Lorem Ipsum is simply dummy text of the printing and typesetting",
            },
        ],
    },
]
